"""
constant_field.py — arithmetic and geometric Galois groups over F_q[t], q = p
prime, and the constant-field degree relating them.

Two runs of one descent code path on f ∈ F_q[t][x], monic and separable in x,
with roots in S = F_{q^s}[[u]]/u^K at a point t = t_0 (u = t - t_0):

  arithmetic descent   (constant_field_degree e = 1)
      recognition of a resolvent value ρ ∈ S as an element of F_q[t]: the
      series is a polynomial in u of degree ≤ B whose coefficients are fixed by
      the Frobenius of F_{q^s} (the "Frobenius test" on the t-polynomial);
      coset pruning by τ (A2);  result: G = Gal(f / F_q(t)).
  geometric descent    (e = s)
      the same code path with the Frobenius test dropped: coefficients may lie
      in F_{q^s}; no τ-pruning (τ ∉ G_geom in general);
      result: Gal(f / F_{q^s}(t)) = G_geom, because the constant field F_{q^c}
      of the splitting field embeds in F_{q^s} (c | s).

A7 record: c = [G : G_geom] is the constant field degree; verified consistency:
  * G_geom ⊴ G, G/G_geom cyclic of order c generated by the class of τ
    (τ restricts to the Frobenius of F_{q^c}/F_q), c | s;
  * the Frobenius at every other F_q-rational unramified point has the cycle
    type of an element of the coset τ G_geom (all rational points map to the
    same generator of Gal(F_{q^c}/F_q));
  * the arithmetic group equals the geometric group base-changed: G ∩ "e=s
    recognition" recomputed; |G| = c · |G_geom|.

Not implemented here (documented): the starting group from subfields (A6 over
F_q[t]) — the descent starts at S_n; and the direct computation of inertia
groups at ramified places (Theorem 7.3 is therefore not re-verified
numerically, only its consequence c = [G:G_geom] with the Frobenius checks).

The resolvent R and all root tests are exact in F_{q^e}[u] = F_{q^e}[t]
(polynomials in u with coefficients in F_{q^s}); the negative verdict is
complete because every root of R in the ring is one of the coset values.
"""

from __future__ import annotations

import json
import math
import random
from fractions import Fraction
from typing import Dict, FrozenSet, List, Optional, Tuple

import hensel_frobenius as hf
import invariants as inv
import permgroup as pg
from hensel_frobenius import Zmod, PolyQuot, _peval, _strip

Perm = Tuple[int, ...]


# ----------------------------------------------------------------------------
# exact arithmetic in F[u] (F = F_{p^s} as a PolyQuot field), polynomials low->high
# ----------------------------------------------------------------------------

class FuPoly:
    def __init__(self, F: PolyQuot):
        self.F = F
    def norm(self, a):
        a = list(a)
        while a and self.F.is_zero(a[-1]):
            a.pop()
        return a
    def add(self, a, b):
        out = [self.F.zero()] * max(len(a), len(b))
        for i, x in enumerate(a): out[i] = self.F.add(out[i], x)
        for i, x in enumerate(b): out[i] = self.F.add(out[i], x)
        return self.norm(out)
    def mul(self, a, b):
        if not a or not b: return []
        out = [self.F.zero()] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            if self.F.is_zero(x): continue
            for j, y in enumerate(b):
                out[i + j] = self.F.add(out[i + j], self.F.mul(x, y))
        return self.norm(out)
    def scal(self, a, c):
        return self.norm([self.F.mul(c, x) for x in a])
    def is_zero(self, a): return not self.norm(a)
    def eq(self, a, b): return self.is_zero(self.add(a, self.norm([self.F.neg(x) for x in b])))
    def deg(self, a): a = self.norm(a); return len(a) - 1 if a else -1
    def eval_x(self, Rx, v):
        """R(v) for R ∈ F[u][x] (list in x of F[u]-polys), v ∈ F[u]."""
        acc = []
        for c in reversed(Rx):
            acc = self.add(self.mul(acc, v), c)
        return acc
    def deriv_x(self, Rx):
        return [self.scal(Rx[i], self.F.from_int(i)) for i in range(1, len(Rx))]


# ----------------------------------------------------------------------------
# the function-field descent state
# ----------------------------------------------------------------------------

class FqtState:
    def __init__(self, f_t: List[List[int]], p: int, t0: int, K: int = 40, table_path: str = "tables/invariants_descent.json"):
        self.f_t, self.p, self.t0 = f_t, p, t0
        self.n = len(f_t) - 1
        self.ic = inv.InvariantConstructor(table_path)
        self.K = 0
        self.roots_raw = None
        self.T: Optional[List[int]] = None
        self.ensure_precision(K)
        # root degree bound (Newton polygon at infinity): δ = max_j deg(a_j)/(n-j)
        Fp = Zmod(p)
        degs = [(len(_strip(Fp, a)) - 1, j) for j, a in enumerate(f_t[:-1]) if _strip(Fp, a)]
        self.delta = max((Fraction(d, self.n - j) for d, j in degs), default=Fraction(0))   # exact (float rounding here breaks the degree bounds)

    def ensure_precision(self, K: int):
        if K <= self.K:
            return
        ob = hf.case3(self.f_t, self.p, self.t0, K, return_objects=True)
        if self.roots_raw is not None:
            for old, new in zip(self.roots_raw, ob["roots"]):
                assert all(self.F.eq(a, b) for a, b in zip(old[: self.K], new[: self.K])), "relabelling on precision increase"
            assert tuple(ob["tau"]) == self.tau
        self.S, self.F, self.roots_raw, self.phi, self.tau, self.s, self.K = ob["S"], ob["F"], ob["roots"], ob["phi"], tuple(ob["tau"]), ob["s"], K
        self.Fu = FuPoly(self.F)
        self._apply_T()

    def _apply_T(self):
        """T is a Tschirnhaus transformation with coefficients in F_q[t]
        (lists low->high); coefficients from F_q alone are NOT enough — the
        Schwartz-Zippel sample set must exceed the degree of the difference
        polynomial, and F_q is too small for the invariant degrees that occur."""
        if self.T is None:
            self.roots = list(self.roots_raw)
        else:
            Fp = Zmod(self.p)
            TS = [self.S.from_list([self.F.from_int(c) for c in hf._shift_poly_t(self.p, coeff, self.t0)])
                  if _strip(Fp, coeff) else self.S.zero()
                  for coeff in self.T]
            self.roots = [_peval(self.S, TS, r) for r in self.roots_raw]

    def root_degree_bound(self) -> Fraction:
        if self.T is None:
            return self.delta
        Fp = Zmod(self.p)
        best = Fraction(0)
        for k, coeff in enumerate(self.T):
            c = _strip(Fp, coeff)
            if c:
                best = max(best, (len(c) - 1) + k * self.delta)
        return best

    def evaluate(self, Fpoly):
        S = self.S
        acc = S.zero()
        pw = [[S.one()] for _ in self.roots]
        for e, c in Fpoly.items():
            term = S.from_int(c)
            for i, ei in enumerate(e):
                while len(pw[i]) <= ei:
                    pw[i].append(S.mul(pw[i][-1], self.roots[i]))
                if ei: term = S.mul(term, pw[i][ei])
            acc = S.add(acc, term)
        return acc

    def in_constant_field(self, c, e: int) -> bool:
        """c ∈ F_{p^s} lies in F_{p^e}: for e = 1 only the constant coordinate; for e = s always
        (for a general e | s one would test Frobenius^e(c) = c)."""
        if e == self.s:
            return True
        if e == 1:
            return all(self.F.base.is_zero(x) for x in c[1:])
        return self.F.eq(self.F.pow(c, self.p ** e), c)

    def recognize(self, gamma, deg_bound: int, upto: int, e: int) -> Optional[List]:
        """γ ∈ S as a polynomial in u of degree ≤ deg_bound with coefficients in
        F_{p^e}, checked up to u^upto; None if the image check fails."""
        for j in range(deg_bound + 1, min(upto, self.K)):
            if not self.F.is_zero(gamma[j]):
                return None
        coeffs = list(gamma[: deg_bound + 1])
        if not all(self.in_constant_field(c, e) for c in coeffs):
            return None
        return self.Fu.norm(coeffs)


# ----------------------------------------------------------------------------
# descend(U) over F_{p^e}(t)
# ----------------------------------------------------------------------------

def _test_pair(state: FqtState, U: FrozenSet[Perm], V: FrozenSet[Perm], e: int, verbose: bool,
               use_pruning: bool = True, proof: str = "resolvent"):
    n = state.n
    Ug, Vg = pg.generating_set(U, n), pg.generating_set(V, n)
    N_idx = len(U) // len(V)
    rec = state.ic.invariant(Ug, Vg, n)
    Fpoly = rec["F"]
    # pruning (arithmetic descent only)
    Nrm = pg.normalizer(U, V, n)
    reps = pg.coset_reps(U, Nrm)
    if e == 1 and use_pruning:
        surviving = [s_ for s_ in reps if pg.compose(pg.inverse(s_), pg.compose(state.tau, s_)) in V]
        if not surviving:
            if verbose: print(f"    V order {len(V):3d} idx {N_idx:2d} | dismissed by pruning (tau in no conjugate)")
            state.last_pair = {"kind": "dismissed_by_pruning", "V_order": len(V)}
            return None
    else:
        surviving = reps
    d = max(sum(ex) for ex in Fpoly)
    B = d * state.root_degree_bound()                 # exact Fraction
    Bi = math.floor(B)
    NB = math.floor(N_idx * B)
    k_rec, k_prf = Bi + 1, NB + 1
    k2 = k_rec + max(4, k_rec // 2)
    if proof == "probabilistic":
        state.ensure_precision(k2 + 2)
        cosets_p = pg.coset_reps(U, V)
        allowed = [s_ for s_ in cosets_p if any(pg.compose(pg.inverse(r), s_) in Nrm for r in surviving)]
        for s_ in allowed:
            val = state.evaluate(pg.act(s_, Fpoly))
            v1 = state.recognize(val, Bi, k_rec, e)
            v2 = state.recognize(val, Bi, k2, e)
            if v1 is not None and v2 is not None and state.Fu.eq(v1, v2):
                return {"V": V, "sigma": s_, "v": v1, "k_rec": k_rec, "k2": k2, "k_prf": k_prf, "B": float(B),
                        "index": N_idx, "type": rec["type"], "pruned": (len(surviving), len(reps)), "T": state.T,
                        "proof": "probabilistic"}
        state.last_pair = {"kind": "negative_probabilistic", "V_order": len(V), "k_rec": k_rec, "k2": k2}
        return None
    if max(k_prf, k2) + 2 > 500:
        raise ArithmeticError(f"precision cap: k_prf = {k_prf} for deg F = {d}, T = {state.T} (Tschirnhaus degree too high)")
    state.ensure_precision(max(k_prf, k2) + 2)
    cosets = pg.coset_reps(U, V)
    values = {s_: state.evaluate(pg.act(s_, Fpoly)) for s_ in cosets}
    # exact resolvent in F_{p^e}[u]
    R_S = hf.poly_from_roots(state.S, [values[s_] for s_ in cosets])
    Rx = []
    for c in R_S:
        cu = state.recognize(c, NB, state.K, e)
        assert cu is not None, "resolvent coefficient not in F_{p^e}[t]: G not contained in U, or bound violated"
        Rx.append(cu)
    dRx = state.Fu.deriv_x(Rx)
    ring_roots = {}
    for s_ in cosets:
        v1 = state.recognize(values[s_], Bi, k_rec, e)
        v2 = state.recognize(values[s_], Bi, k2, e)
        if v1 is None or v2 is None or not state.Fu.eq(v1, v2):
            continue                                   # not a polynomial value of degree <= B: not in the ring
        if state.Fu.is_zero(state.Fu.eval_x(Rx, v1)):
            key = tuple(tuple(x) for x in v1)
            ring_roots.setdefault(key, (v1, []))[1].append(s_)
    if verbose:
        print(f"    V order {len(V):3d} idx {N_idx:2d} type {rec['type']:3s} | B={float(B):.2f} k_rec={k_rec} k2={k2} k_prf={k_prf} K={state.K} "
              f"| pruning {len(surviving)}/{len(reps)} | ring roots of R: {len(ring_roots)}")
    if not ring_roots:
        state.last_pair = {"kind": "negative_resolvent", "V_order": len(V), "k_prf": k_prf, "deg_R_in_u": max(state.Fu.deg(c) for c in Rx)}
        return None
    simple = [(v, cs) for v, cs in ring_roots.values() if not state.Fu.is_zero(state.Fu.eval_x(dRx, v))]
    if not simple:
        return "tschirnhaus"
    v, cs = simple[0]
    assert len(cs) == 1
    s_ = cs[0]
    s_class = next(r for r in reps if pg.compose(pg.inverse(r), s_) in Nrm)
    assert s_class in surviving, "pruning discarded a coset containing G"
    return {"V": V, "sigma": s_, "v": v, "k_rec": k_rec, "k2": k2, "k_prf": k_prf, "B": float(B), "index": N_idx, "type": rec["type"],
            "pruned": (len(surviving), len(reps)), "T": state.T}

def descend(state: FqtState, U: FrozenSet[Perm], e: int, verbose: bool = True, max_tschirnhaus: Optional[int] = None,
            use_pruning: bool = True, proof: str = "resolvent"):
    n = state.n
    reps = pg.maximal_subgroup_classes(U, n)
    if verbose:
        print(f"  U of order {len(U)}: maximal classes of orders {[len(V) for V in reps]}")
    rng = random.Random(7)
    if max_tschirnhaus is None:
        max_tschirnhaus = n + 6            # deg_x T must be able to reach n-1 (full Vandermonde span)
    for V in reps:
        state.T = None; state._apply_T()
        verdict = "inconclusive"
        for attempt in range(max_tschirnhaus + 1):
            res = _test_pair(state, U, V, e, verbose, use_pruning=use_pruning, proof=proof)
            if res == "tschirnhaus":
                # low x-degree first (B grows linearly in deg_x T), escalating all the
                # way to n-1: for structured roots (e.g. Kummer) the tuple (T(alpha_j))
                # spans only the first deg T + 1 Vandermonde columns, so persistent
                # coincidences on that subspace are only broken at full degree.
                # Coefficients in F_q[t] of growing t-degree (sample set, Lemma 9.2).
                degT = min(n - 1, 1 + 2 * attempt)   # Kummer character-sum degeneracies need deg T ~ block size
                degc = 1 + attempt // 4
                state.T = [[rng.randrange(state.p) for _ in range(degc + 1)] for _ in range(degT + 1)]
                if all(all(x == 0 for x in c) for c in state.T[1:]):
                    state.T[-1] = [1]
                if state.T == [[0], [1]]:
                    state.T = [[0, 1], [1]]                   # x + t instead of the identity
                state._apply_T()
                if verbose: print(f"    multiple root -> Tschirnhaus T = {state.T}")
                continue
            if res is not None:
                state.T = None; state._apply_T()
                return res
            verdict = "negative"; break
        state.T = None; state._apply_T()
        if verdict != "negative":
            raise ArithmeticError("inconclusive class: G = U not certified")
    return None

def galois_group_Fqt(state: FqtState, e: int, verbose: bool = True, U0: FrozenSet[Perm] = None,
                     use_pruning: bool = True, proof: str = "resolvent") -> Tuple[FrozenSet[Perm], List[Dict]]:
    """U0: optional justified starting group containing G (e.g. the proven
    fibration/torsor bound for sparse families); default S_n."""
    n = state.n
    U = U0 if U0 is not None else pg.closure(inv.S_n(n), n)
    if U0 is not None:
        assert state.tau in U, "certified Frobenius not in the claimed starting group"
    steps = []
    while True:
        res = descend(state, U, e, verbose, use_pruning=use_pruning, proof=proof)
        if res is None:
            break
        U = pg.conjugate(res["V"], res["sigma"])
        steps.append({k: res[k] for k in ("index", "type", "k_rec", "k2", "k_prf", "B", "pruned", "T")} | {"new_order": len(U)})
        if verbose: print(f"  -> group of order {len(U)} (index {res['index']}, v of degree {state.Fu.deg(res['v'])} in u)")
    return U, steps


# ----------------------------------------------------------------------------
# A7: constant field degree and its checks
# ----------------------------------------------------------------------------

def frobenius_cycle_types_at_points(f_t, p, K=6) -> Dict[int, List[int]]:
    """cycle type of the Frobenius at every F_p-rational point with squarefree specialization."""
    out = {}
    for t1 in range(p):
        try:
            r = hf.case3(f_t, p, t1, K)
            out[t1] = r["cycle_type"]
        except (ArithmeticError, AssertionError):
            pass
    return out

def run_A7(f_t: List[List[int]], p: int, t0: int, K: int = 40, verbose: bool = True) -> Dict:
    n = len(f_t) - 1
    state = FqtState(f_t, p, t0, K)
    if verbose:
        print(f"f = {f_t} over F_{p}[t], point t0 = {t0}, residue degree s = {state.s}, tau = {state.tau} (cycle type {hf.cycle_type(state.tau)})")
        print("arithmetic descent over F_%d(t):" % p)
    G, steps_G = galois_group_Fqt(state, e=1, verbose=verbose)
    if verbose:
        print(f"geometric descent over F_{p}^{state.s}(t) (Frobenius test dropped):")
    Ggeo, steps_geo = galois_group_Fqt(state, e=state.s, verbose=verbose)
    # ---- checks ----
    assert Ggeo <= G, "geometric group not contained in the arithmetic group"
    c = len(G) // len(Ggeo)
    normal = all(pg.conjugate(Ggeo, g) == Ggeo for g in pg.generating_set(G, n))
    tau = state.tau
    assert tau in G, "tau not in G"
    # order of tau modulo G_geom
    k, x = 1, tau
    while x not in Ggeo:
        x = pg.compose(tau, x); k += 1
        assert k <= len(G)
    tau_order_mod = k
    # quotient cyclic generated by tau: the cosets tau^i G_geom, i < c, cover G
    cosets_by_tau = set()
    x = pg.identity(n)
    for i in range(c):
        cosets_by_tau |= {pg.compose(x, g) for g in Ggeo}
        x = pg.compose(tau, x)
    quotient_cyclic_by_tau = (cosets_by_tau == set(G))
    c_divides_s = (state.s % c == 0)
    # Frobenius classes at other rational points lie in the generator coset tau G_geom
    gen_coset_types = {tuple(hf.cycle_type(pg.compose(tau, g))) for g in Ggeo}
    frobs = frobenius_cycle_types_at_points(f_t, p)
    frob_ok = {t1: tuple(ct) in gen_coset_types for t1, ct in frobs.items()}
    record = {
        "f": f_t, "p": p, "t0": t0, "s": state.s, "tau": list(tau), "tau_cycle_type": hf.cycle_type(tau),
        "G_order": len(G), "G_gens": [list(g) for g in pg.generating_set(G, n)],
        "G_geom_order": len(Ggeo), "G_geom_gens": [list(g) for g in pg.generating_set(Ggeo, n)],
        "constant_field_degree_c": c,
        "checks": {"G_geom_normal_in_G": normal, "tau_order_mod_G_geom_equals_c": tau_order_mod == c,
                   "quotient_cyclic_generated_by_tau": quotient_cyclic_by_tau, "c_divides_s": c_divides_s,
                   "frobenius_at_rational_points_in_generator_coset": frob_ok},
        "steps_arithmetic": steps_G, "steps_geometric": steps_geo,
        "notes": ["starting group S_n (A6 over F_q[t] not implemented)",
                  "inertia groups at ramified places not computed; Theorem 7.3 not re-verified directly"],
    }
    record["all_checks_pass"] = normal and tau_order_mod == c and quotient_cyclic_by_tau and c_divides_s and all(frob_ok.values())
    if verbose:
        print(f"  |G| = {len(G)}, |G_geom| = {len(Ggeo)}, constant field degree c = {c}; checks: {record['checks']}")
    return record


if __name__ == "__main__":
    examples = [
        ("x^3 - t^2 over F_5  (S_3, geometric A_3: c = 2)",   [[0, 0, 4], [0], [0], [1]], 5, 1),
        ("x^3 - t^2 over F_7  (C_3 = geometric: c = 1)",      [[0, 0, 6], [0], [0], [1]], 7, 1),
        ("x^3 + t x + 1 over F_5 (S_3 = geometric: c = 1)",   [[1], [0, 1], [0], [1]], 5, 1),
        ("x^2 - 2 over F_5 (constant extension: c = 2)",      [[3], [0], [1]], 5, 0),
        ("x^2 - t over F_5 (C_2 = geometric: c = 1)",         [[0, 4], [0], [1]], 5, 4),
    ]
    out = {}
    for name, f_t, p, t0 in examples:
        print("=" * 90); print(name)
        rec = run_A7(f_t, p, t0)
        out[name] = {k: rec[k] for k in ("G_order", "G_geom_order", "constant_field_degree_c", "all_checks_pass")}
    print("=" * 90)
    print(json.dumps(out, indent=2))
