"""
permgroup.py — the permutation-group library shared by the prover (invariants,
descent) and the independent checker. This is the ONLY code the checker shares
with the prover.

Permutations are tuples (images of 0..n-1); (a∘b)(i) = a(b(i)). Polynomials
acted upon are sparse dicts {exponent tuple: integer coefficient}, with
(g·F)(x_0..x_{n-1}) obtained by x_i ↦ x_{g(i)}.

Everything is brute force (closures by breadth-first search, complete subgroup
enumeration by one-generator extensions); adequate for |U| up to a few
thousand, and the only part that would change at scale (Schreier–Sims).
"""

from __future__ import annotations

from typing import Dict, FrozenSet, List, Optional, Sequence, Tuple

Perm = Tuple[int, ...]
Poly = Dict[Tuple[int, ...], int]

# ----------------------------------------------------------------------------
# permutations and groups
# ----------------------------------------------------------------------------

def identity(n: int) -> Perm:
    return tuple(range(n))

def compose(a: Perm, b: Perm) -> Perm:          # (a∘b)(i) = a(b(i))
    return tuple(a[b[i]] for i in range(len(a)))

def inverse(a: Perm) -> Perm:
    inv = [0] * len(a)
    for i, ai in enumerate(a):
        inv[ai] = i
    return tuple(inv)

def closure(gens: Sequence[Perm], n: int, cap: int = 2_000_000, stop_above: Optional[int] = None) -> FrozenSet[Perm]:
    """all elements of ⟨gens⟩ by BFS. If stop_above is given, stop as soon as the
    size exceeds it (used for 'is this already the whole group' questions)."""
    e = identity(n)
    seen = {e}
    frontier = [e]
    while frontier:
        nxt = []
        for g in frontier:
            for h in gens:
                gh = compose(h, g)
                if gh not in seen:
                    seen.add(gh)
                    nxt.append(gh)
                    if len(seen) > cap:
                        raise ArithmeticError("group too large for brute-force closure")
                    if stop_above is not None and len(seen) > stop_above:
                        return frozenset(seen)
        frontier = nxt
    return frozenset(seen)

def generating_set(elems: FrozenSet[Perm], n: int) -> List[Perm]:
    gens: List[Perm] = []
    cur = frozenset({identity(n)})
    for g in sorted(elems):
        if g not in cur:
            gens.append(g)
            cur = closure(gens, n)
            if len(cur) == len(elems):
                break
    return gens

def is_transitive(elems: FrozenSet[Perm], n: int) -> bool:
    return len({g[0] for g in elems}) == n

def is_maximal_bruteforce(U: FrozenSet[Perm], V: FrozenSet[Perm], n: int) -> bool:
    """V maximal in U iff ⟨V, g⟩ = U for every g ∈ U \\ V."""
    vg = generating_set(V, n)
    half = len(U) // 2
    for g in U:
        if g in V:
            continue
        if len(closure(vg + [g], n, stop_above=half)) <= half:
            return False
    return True

def maximal_overgroup(U: FrozenSet[Perm], V: FrozenSet[Perm], n: int) -> FrozenSet[Perm]:
    """some maximal subgroup W of U with V ≤ W < U (requires V < U)."""
    assert V < U
    M = V
    while True:
        mg = generating_set(M, n)
        best = None
        for g in U:
            if g in M:
                continue
            C = closure(mg + [g], n)
            if len(C) < len(U) and (best is None or len(C) > len(best)):
                best = C
        if best is None:
            return M
        M = best

def conjugate(S: FrozenSet[Perm], u: Perm) -> FrozenSet[Perm]:
    ui = inverse(u)
    return frozenset(compose(u, compose(g, ui)) for g in S)

_SUBGROUP_CACHE: Dict[FrozenSet[Perm], List[FrozenSet[Perm]]] = {}

def all_subgroups(U: FrozenSet[Perm], n: int, cap: int = 800) -> List[FrozenSet[Perm]]:
    """every subgroup of U, by extending known subgroups one generator at a time
    (this reaches every subgroup, since any subgroup is generated by finitely
    many elements). Memoised per group. For |U| > cap the caller must not rely
    on completeness."""
    if U in _SUBGROUP_CACHE:
        return _SUBGROUP_CACHE[U]
    if len(U) > cap:
        raise ArithmeticError(f"|U| = {len(U)} exceeds the brute-force subgroup enumeration cap {cap}")
    # conjugacy-aware reuse: if a conjugate group pi U' pi^{-1} = U is cached, transport its subgroups
    n = len(next(iter(U)))
    if n <= 8 and len(U) > 100:            # for small groups direct enumeration beats the n!-scan
        import itertools as _it
        for Uc, subsc in list(_SUBGROUP_CACHE.items()):
            if len(Uc) != len(U) or len(next(iter(Uc))) != n:
                continue
            Ug = generating_set(Uc, n)
            for pi in _it.permutations(range(n)):
                pinv = inverse(pi)
                if all(compose(pi, compose(g, pinv)) in U for g in Ug):
                    out = [frozenset(compose(pi, compose(g, pinv)) for g in S) for S in subsc]
                    out = sorted(out, key=lambda S: (len(S), sorted(S)))
                    _SUBGROUP_CACHE[U] = out
                    return out
    elems = sorted(U)
    e = identity(n)
    subs = {frozenset({e})}
    frontier = [frozenset({e})]
    while frontier:
        nxt = []
        for S in frontier:
            Sg = generating_set(S, n)
            covered = set(S)                      # <S, g> = <S, s g>: one g per right coset S g suffices
            for g in elems:
                if g in covered:
                    continue
                covered |= {compose(x, g) for x in S}
                T = closure(Sg + [g], n)
                if T not in subs:
                    subs.add(T); nxt.append(T)
        frontier = nxt
    out = sorted(subs, key=lambda S: (len(S), sorted(S)))     # canonical order: results must not depend on set iteration
    _SUBGROUP_CACHE[U] = out
    return out


def save_subgroup_cache(path: str = "tables/subgroup_cache.pkl"):
    import os, pickle
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as fh:
        pickle.dump(_SUBGROUP_CACHE, fh)

def load_subgroup_cache(path: str = "tables/subgroup_cache.pkl"):
    import os, pickle
    if os.path.exists(path):
        with open(path, "rb") as fh:
            _SUBGROUP_CACHE.update(pickle.load(fh))

def maximal_subgroup_classes(U: FrozenSet[Perm], n: int) -> List[FrozenSet[Perm]]:
    """representatives of the conjugacy classes of maximal subgroups of U,
    from the complete subgroup list (sound: no maximal subgroup is missed)."""
    subs = all_subgroups(U, n)
    proper = [S for S in subs if len(S) < len(U)]
    maximal = [S for S in proper if not any(S < T for T in proper)]
    reps: List[FrozenSet[Perm]] = []
    for S in sorted(maximal, key=lambda S: (-len(S), sorted(S))):
        if any(conjugate(S, u) in reps for u in U):
            continue
        reps.append(S)
    return reps

def normalizer(U: FrozenSet[Perm], V: FrozenSet[Perm], n: int) -> FrozenSet[Perm]:
    Vg = generating_set(V, n)
    return frozenset(u for u in U if all(compose(u, compose(g, inverse(u))) in V for g in Vg))

def coset_reps(U: FrozenSet[Perm], N: FrozenSet[Perm]) -> List[Perm]:
    reps, covered = [], set()
    for u in sorted(U):
        if u in covered:
            continue
        reps.append(u)
        covered |= {compose(u, h) for h in N}
    return reps



def act(g: Perm, F: Poly) -> Poly:
    """(g·F): x_i ↦ x_{g(i)}."""
    out: Poly = {}
    n = len(g)
    for e, c in F.items():
        e2 = [0] * n
        for i, ei in enumerate(e):
            e2[g[i]] = ei
        out[tuple(e2)] = c
    return out

def reduce_mod(F: Poly, p: int) -> Poly:
    return {e: c % p for e, c in F.items() if c % p}

def degree(F: Poly) -> int:
    return max(sum(e) for e in F) if F else -1

def canon(F: Poly):
    return frozenset(F.items())

def verify_stabilizer(U_gens: Sequence[Perm], U_order: int, V_gens: Sequence[Perm], V_order: int, F: Poly, n: int) -> Dict:
    """Stab_U(F) = V by orbit counting, over Z and modulo 2 and 3."""
    assert U_order % V_order == 0
    index = U_order // V_order
    report = {"index": index}
    for label, Fm in (("Z", F), ("mod2", reduce_mod(F, 2)), ("mod3", reduce_mod(F, 3))):
        if not Fm:
            report[label] = {"ok": False, "reason": "zero polynomial"}
            continue
        fixed = all(canon(act(v, Fm)) == canon(Fm) for v in V_gens)
        seen = {canon(Fm)}
        frontier = [Fm]
        too_big = False
        while frontier and not too_big:
            nxt = []
            for P in frontier:
                for g in U_gens:
                    Q = act(g, P)
                    k = canon(Q)
                    if k not in seen:
                        seen.add(k); nxt.append(Q)
                        if len(seen) > index:
                            too_big = True; break
                if too_big:
                    break
            frontier = nxt
        report[label] = {"ok": fixed and not too_big and len(seen) == index, "fixed_by_V": fixed, "orbit_size": len(seen)}
    report["ok"] = all(report[k]["ok"] for k in ("Z", "mod2", "mod3"))
    return report
