"""
family_sparse.py — validation family 3: specializations to F_q(t) of lacunary
and triangular sparse systems with mixed volume up to 40.

Families (univariate pencils; MV = deg_x f = number of solutions):

  A. pure lacunary      f = x^d - t                (MV = d, up to 40)
  B. lacunary trinomial f = x^{dm} - x^d - t = g(x^d), g = y^m - y - t
                                                   (MV = dm, up to 16)
  C. triangular         f = g(h(x)) for sparse g, h (MV = 6 here)

Classification (Esterov's dichotomy, specialized to a one-parameter pencil;
the containments below are PROVEN for every pencil, equality holds for the
full coefficient space and is expected/observed for generic pencils):

  * the fibres of x -> x^d and the mu_d-torsor structure on each fibre are
    defined over F_q(t); every Galois element acts on a fixed primitive
    zeta_d by a single power (the cyclotomic character). Hence in the natural
    labelling (fibre i, cyclic label k):

        G_geom <= W_cl = C_d wr S_m            (multiplier 1)
        G      <= A_cl = (C_d wr S_m) x| <q mod d>   (global multiplier in <q>)

    and the certified Frobenius at any F_q-point has multiplier exactly q.
  * [G : G_geom] = c is the constant field degree (A7); for the pencils here
    the constants are generated by zeta_d (the base g = y^m - y - t has c = 1),
    so the prediction is c = ord_d(q).
  * triangular: fibre blocks of h are proven; the block quotient of G_geom is
    the geometric monodromy of g (computed independently), and
    G_geom <= L wr (quotient) for the relative local group L.

Everything group-theoretic is checked as literal containment of permutation
sets in the natural labelling — no conjugacy searches. The descent starts at
the PROVEN bound A_cl (recorded in the result), which is what makes MV = 40
feasible (|A_cl| = d phi(d) = 640 for d = 40, versus |S_40|).

Results accumulate in family_sparse_results.json (resumable, time budget).
"""

from __future__ import annotations

import json
import math
import os
import sys
import time
from typing import Dict, FrozenSet, List, Optional, Tuple

import constant_field as cf
import hensel_frobenius as hf
import invariants as inv
import permgroup as pg

Perm = Tuple[int, ...]


def ord_mod(q: int, d: int) -> int:
    if d == 1:
        return 1
    s, x = 1, q % d
    while x != 1:
        x = (x * q) % d; s += 1
    return s

# ----------------------------------------------------------------------------
# fibration labelling and the classification groups in that labelling
# ----------------------------------------------------------------------------

def fibration_labels(state: cf.FqtState, d: int) -> Tuple[List[Tuple[int, int]], object]:
    """label each root as (fibre i, cyclic label k): roots in one fibre of
    x -> x^d differ by d-th roots of unity zeta^k (constants of F_{q^s});
    returns labels and the chosen primitive zeta."""
    S, F = state.S, state.F
    n = state.n
    roots = state.roots_raw
    pw = [S.pow(r, d) for r in roots]
    fibres: List[List[int]] = []
    for j in range(n):
        for fb in fibres:
            if S.eq(pw[fb[0]], pw[j]):
                fb.append(j); break
        else:
            fibres.append([j])
    assert all(len(fb) == d for fb in fibres), "fibres of x -> x^d are not uniform"
    # ratios within a fibre are constants (d-th roots of unity)
    def const_of(x):
        assert all(F.is_zero(c) for c in x[1:]), "root ratio is not constant: not a mu_d-torsor"
        return x[0]
    inv0 = S.inv(roots[fibres[0][0]])
    ratios = [const_of(S.mul(roots[j], inv0)) for j in fibres[0]]
    zeta = None
    for r in ratios:
        # order of r in F^*
        o, x = 1, r
        while not F.eq(x, F.one()):
            x = F.mul(x, r); o += 1
        if o == d:
            zeta = r; break
    assert zeta is not None, "no primitive d-th root of unity among the ratios"
    zpow = [F.one()]
    for _ in range(d - 1):
        zpow.append(F.mul(zpow[-1], zeta))
    labels: List[Optional[Tuple[int, int]]] = [None] * n
    for i, fb in enumerate(fibres):
        base = roots[fb[0]]
        binv = S.inv(base)
        for j in fb:
            c = const_of(S.mul(roots[j], binv))
            k = next(k for k in range(d) if F.eq(c, zpow[k]))
            labels[j] = (i, k)
    return labels, zeta

def classification_groups(labels: List[Tuple[int, int]], d: int, m: int, q: int):
    """W_cl = C_d wr S_m and A_cl = W_cl x| <q mod d> in the root labelling."""
    n = d * m
    idx = {lab: j for j, lab in enumerate(labels)}
    def perm_from_map(fmap):
        out = [0] * n
        for j, (i, k) in enumerate(labels):
            out[j] = idx[fmap(i, k)]
        return tuple(out)
    gens_W = [perm_from_map(lambda i, k: (i, (k + 1) % d) if i == 0 else (i, k))]
    if m >= 2:
        gens_W.append(perm_from_map(lambda i, k: ({0: 1, 1: 0}.get(i, i), k)))
        gens_W.append(perm_from_map(lambda i, k: ((i + 1) % m, k)))
    W_cl = pg.closure(gens_W, n)
    gens_A = gens_W + [perm_from_map(lambda i, k: (i, (q * k) % d))]
    A_cl = pg.closure(gens_A, n)
    return W_cl, A_cl

def affine_data(perm: Perm, labels, d: int, m: int):
    """if perm maps (i,k) -> (sigma(i), u k + b_i) with one multiplier u, return
    (u, sigma, b); else None."""
    idx = {lab: j for j, lab in enumerate(labels)}
    sigma = {}
    u_global = None
    b = {}
    for i in range(m):
        j0 = idx[(i, 0)]
        i2, b_i = labels[perm[j0]]
        sigma[i] = i2; b[i] = b_i
        if d >= 2:
            j1 = idx[(i, 1)]
            i2b, k2 = labels[perm[j1]]
            if i2b != i2:
                return None
            u = (k2 - b_i) % d
            if u_global is None:
                u_global = u
            elif u != u_global:
                return None
    if u_global is None:
        u_global = 1
    for j, (i, k) in enumerate(labels):
        i2, k2 = labels[perm[j]]
        if i2 != sigma[i] or k2 != (u_global * k + b[i]) % d:
            return None
    return u_global, sigma, b


# ----------------------------------------------------------------------------
# one lacunary pencil (families A and B)
# ----------------------------------------------------------------------------

def check_lacunary(q: int, d: int, m: int, K: int = 30, verbose: bool = True, phase: int = None) -> Dict:
    n = d * m
    assert q % 2 == 1 and math.gcd(d * m, q) == 1 and math.gcd(m - 1 if m > 1 else 1, q) == 1
    if m == 1:
        f_t = [[0, q - 1]] + [[0]] * (n - 1) + [[1]]                     # x^d - t
    else:
        f_t = [[0, q - 1]] + [[0]] * (d - 1) + [[q - 1]] + [[0]] * (n - d - 1) + [[1]]   # x^{dm} - x^d - t
    rec: Dict = {"family": "A" if m == 1 else "B", "q": q, "d": d, "m": m, "MV": n, "f": f_t}
    # a point with squarefree specialization
    t0 = None
    Fp = hf.Zmod(q)
    import verify_roots as vr
    for cand in range(q):
        f0 = [hf._peval(Fp, a, cand) for a in f_t]
        if vr._is_squarefree(Fp, f0):
            t0 = cand; break
    assert t0 is not None
    rec["t0"] = t0
    state = cf.FqtState(f_t, q, t0, K)
    rec["s"] = state.s
    labels, _ = fibration_labels(state, d)
    W_cl, A_cl = classification_groups(labels, d, m, q)
    rec["W_cl_order"], rec["A_cl_order"] = len(W_cl), len(A_cl)
    # certified Frobenius: affine with multiplier exactly q
    aff = affine_data(state.tau, labels, d, m)
    rec["tau_affine_multiplier_q"] = aff is not None and aff[0] == q % d
    # descent from the proven bound A_cl (arithmetic), then geometric from G (G_geom <= G, tau in G).
    # phase support: for large pencils the two descents run in separate invocations,
    # with G's generators passed through a scratch file (the state rebuild is deterministic).
    import os
    scratch = f"scratch_lacunary_{q}_{d}_{m}.json"
    if os.path.exists(scratch):
        G = pg.closure([tuple(x) for x in json.load(open(scratch))["G_gens"]], n)
        assert state.tau in G and G <= A_cl
    else:
        G, _ = cf.galois_group_Fqt(state, e=1, verbose=False, U0=A_cl)
        if phase == 1:
            json.dump({"G_gens": [list(g) for g in pg.generating_set(G, n)]}, open(scratch, "w"))
            rec["phase1_G_order"] = len(G)
            return rec
    Ggeo, _ = cf.galois_group_Fqt(state, e=state.s, verbose=False, U0=G)
    if os.path.exists(scratch):
        os.remove(scratch)
    assert Ggeo <= G
    c = len(G) // len(Ggeo)
    rec["G_order"], rec["G_geom_order"], rec["c"] = len(G), len(Ggeo), c
    # classification comparisons (literal containment in the labelling)
    rec["G_geom_in_W_cl"] = Ggeo <= W_cl
    rec["G_in_A_cl"] = G <= A_cl
    ad_geo = [affine_data(x, labels, d, m) for x in Ggeo]
    rec["G_geom_multipliers_trivial"] = all(a is not None and a[0] % d == 1 % d for a in ad_geo)
    powers_of_q = {pow(q, a, d) for a in range(ord_mod(q, d))} if d > 1 else {0}
    ad_all = [affine_data(x, labels, d, m) for x in G]
    rec["G_multipliers_in_<q>"] = all(a is not None and (a[0] in powers_of_q if d > 1 else True) for a in ad_all)
    rec["c_equals_ord_d_q"] = (c == ord_mod(q, d))
    rec["G_geom_equals_W_cl"] = (Ggeo == W_cl)
    rec["G_equals_A_cl_semidirect"] = (len(G) == len(W_cl) * ord_mod(q, d)) if rec["G_geom_equals_W_cl"] else None
    rec["ok"] = all(rec[k] for k in ("tau_affine_multiplier_q", "G_geom_in_W_cl", "G_in_A_cl",
                                     "G_geom_multipliers_trivial", "G_multipliers_in_<q>", "c_equals_ord_d_q"))
    if verbose:
        print(f"F_{q} d={d:2d} m={m} MV={n:2d}: |W_cl|={len(W_cl):4d} |G_geom|={len(Ggeo):4d} "
              f"{'= W_cl' if rec['G_geom_equals_W_cl'] else '< W_cl'} | |G|={len(G):4d} <= |A_cl|={len(A_cl):4d} "
              f"| c={c} (= ord_{d}({q}): {rec['c_equals_ord_d_q']}) | {'all ok' if rec['ok'] else 'FAILURE'}")
    return rec


# ----------------------------------------------------------------------------
# triangular pencils (family C)
# ----------------------------------------------------------------------------

def _compose_ft(g_t, h_t, q):
    """g(h(x)) for polynomials with F_q[t] coefficients (lists of lists)."""
    def norm(a):
        a = [c % q for c in a]
        while a and a[-1] == 0: a.pop()
        return a
    def add(a, b):
        out = [0] * max(len(a), len(b))
        for i, x in enumerate(a): out[i] += x
        for i, x in enumerate(b): out[i] += x
        return norm(out)
    def mul(a, b):
        if not a or not b: return []
        out = [0] * (len(a) + len(b) - 1)
        for i, x in enumerate(a):
            for j, y in enumerate(b):
                out[i + j] += x * y
        return norm(out)
    def pxmul(A, B):
        out = [[] for _ in range(len(A) + len(B) - 1)]
        for i, a in enumerate(A):
            for j, b in enumerate(B):
                out[i + j] = add(out[i + j], mul(a, b))
        return out
    out = [[]]
    for c in reversed(g_t):
        out = pxmul(out, h_t)
        out[0] = add(out[0], c)
    while len(out) > 1 and not out[-1]:
        out.pop()
    return [a if a else [0] for a in out]

def check_triangular(q: int, g_t, h_t, name: str, K: int = 30, verbose: bool = True) -> Dict:
    f_t = _compose_ft(g_t, h_t, q)
    n = len(f_t) - 1
    mh = len(h_t) - 1
    mg = len(g_t) - 1
    rec: Dict = {"family": "C", "name": name, "q": q, "MV": n, "deg_g": mg, "deg_h": mh, "f": f_t}
    import verify_roots as vr
    Fp = hf.Zmod(q)
    t0 = next(c for c in range(q) if vr._is_squarefree(Fp, [hf._peval(Fp, a, c) for a in f_t]))
    rec["t0"] = t0
    state = cf.FqtState(f_t, q, t0, K)
    # fibre blocks of h (proven): group roots by h(root)
    S = state.S
    h_S = [S.from_list([state.F.from_int(c) for c in hf._shift_poly_t(q, a, t0)]) for a in h_t]
    vals = [hf._peval(S, h_S, r) for r in state.roots_raw]
    blocks: List[List[int]] = []
    for j in range(n):
        for bl in blocks:
            if S.eq(vals[bl[0]], vals[j]):
                bl.append(j); break
        else:
            blocks.append([j])
    assert len(blocks) == mg and all(len(b) == mh for b in blocks)
    P = inv._canon(blocks)
    # starting group: full block stabilizer (proven since the fibration is over F_q(t)); small n only
    assert n <= 7, "triangular starting group is built by S_n enumeration (n <= 7)"
    Sm_top = pg.closure(inv.S_n(n), n)
    U0 = frozenset(x for x in Sm_top if all(frozenset(x[i] for i in b) in {frozenset(b2) for b2 in blocks} for b in blocks))
    G, _ = cf.galois_group_Fqt(state, e=1, verbose=False, U0=U0)
    Ggeo, _ = cf.galois_group_Fqt(state, e=state.s, verbose=False, U0=U0)
    c = len(G) // len(Ggeo)
    rec["G_order"], rec["G_geom_order"], rec["c"] = len(G), len(Ggeo), c
    # block quotient of G_geom vs the independently computed geometric monodromy of g
    piGgeo = frozenset(inv.induced_action(x, P) for x in Ggeo)
    rg = cf.run_A7(g_t, q, next(cc for cc in range(q) if vr._is_squarefree(Fp, [hf._peval(Fp, a, cc) for a in g_t])), verbose=False)
    rec["Mg_geom_order"] = rg["G_geom_order"]
    import itertools as it
    Gg = pg.closure([tuple(x) for x in rg["G_geom_gens"]], mg)
    rec["C1_block_quotient_is_Mg_geom"] = any(all(pg.compose(pi, pg.compose(x, pg.inverse(pi))) in Gg for x in pg.generating_set(piGgeo, mg))
                                              for pi in it.permutations(range(mg))) and len(piGgeo) == len(Gg)
    # local group and the wreath bound
    L, _ = inv.local_group(Ggeo, P[0])
    ker = frozenset(x for x in Ggeo if inv.induced_action(x, P) == pg.identity(mg))
    rec["L_order"], rec["kernel_order"] = len(L), len(ker)
    rec["C2_G_geom_in_L_wr_quotient"] = (len(Ggeo) == len(piGgeo) * len(ker)) and (len(L) ** mg) % len(ker) == 0
    rec["W_cl_order"] = (math.factorial(mh)) ** mg * rec["Mg_geom_order"]     # relative monodromy <= S_mh
    rec["C3_G_geom_in_W_cl"] = len(Ggeo) <= rec["W_cl_order"] and all(all(frozenset(x[i] for i in b) in set(P) for b in P) for x in Ggeo)
    rec["ok"] = all(rec[k] for k in ("C1_block_quotient_is_Mg_geom", "C2_G_geom_in_L_wr_quotient", "C3_G_geom_in_W_cl"))
    if verbose:
        print(f"F_{q} {name} MV={n}: |G|={len(G):3d} |G_geom|={len(Ggeo):3d} c={c} | quotient=M_g^geom({rec['Mg_geom_order']}) "
              f"{rec['C1_block_quotient_is_Mg_geom']} | L={len(L)} kernel={len(ker)} wreath bound {rec['C2_G_geom_in_L_wr_quotient']} | {'all ok' if rec['ok'] else 'FAILURE'}")
    return rec


# ----------------------------------------------------------------------------
# the run
# ----------------------------------------------------------------------------

FAMILY_A = [(5, d) for d in (2, 3, 4, 6, 7, 8, 9, 11, 12, 13, 16, 18, 21, 24, 28, 33, 36)] + \
           [(3, d) for d in (5, 10, 20, 25, 34, 40)] + [(7, 40)]
FAMILY_B = [(5, 2, 2), (5, 3, 2), (5, 2, 3), (7, 2, 2), (7, 3, 2), (5, 4, 2), (7, 4, 2), (5, 2, 4),
            (7, 6, 2), (5, 7, 2), (11, 6, 2), (5, 8, 2), (13, 3, 3)]
FAMILY_C = [(5, [[0, 4], [0], [0], [1]], [[0, 4], [0], [1]], "g=y^3-t o h=x^2-t"),
            (7, [[6, 6], [0], [1]], [[0, 6], [6], [0], [1]], "g=y^2-(t+1) o h=x^3-x-t"),
            (5, [[0, 4], [4], [0], [1]], [[0, 4], [0], [1]], "g=y^3-y-t o h=x^2-t")]

def main(budget_s: Optional[float] = None, results_path: str = "family_sparse_results.json") -> List[Dict]:
    pg.load_subgroup_cache()
    results = json.load(open(results_path)) if os.path.exists(results_path) else []
    done = {json.dumps(r["key"]) for r in results if r.get("status") == "ok"}   # failures are retried
    t_all = time.time()
    jobs = [("A", (q, d, 1)) for q, d in FAMILY_A] + [("B", (q, d, m)) for q, d, m in FAMILY_B] + \
           [("C", (0, i)) for i in range(len(FAMILY_C))]
    for fam, key in jobs:
        kj = json.dumps([fam, key])
        if kj in done:
            continue
        if budget_s is not None and time.time() - t_all > budget_s:
            print(f"[budget reached: {len(results)} of {len(jobs)} jobs recorded]")
            break
        t0 = time.time()
        try:
            if fam in ("A", "B"):
                q, d, m = key
                rec = check_lacunary(q, d, m)
            else:
                q, i = key
                qq, g_t, h_t, name = FAMILY_C[i]
                rec = check_triangular(qq, g_t, h_t, name)
            rec["status"] = "ok"
        except (ArithmeticError, AssertionError) as e:
            rec = {"status": f"failed: {e}"}
            print(f"{fam} {key}: {rec['status']}")
        rec["key"] = [fam, key]
        rec["time_s"] = round(time.time() - t0, 1)
        if rec.get("status") == "ok":                          # drop superseded failed attempts for this key
            results = [r for r in results if r["key"] != rec["key"] or r.get("status") == "ok"]
        results.append(rec)
        pg.save_subgroup_cache()
        with open(results_path, "w") as fh:
            json.dump(results, fh, indent=1, default=str)
    oks = [r for r in results if r.get("status") == "ok"]
    print(f"\n{len(oks)} pencils checked / {len(results)} recorded")
    if oks:
        print("all classification checks pass:", all(r["ok"] for r in oks))
        lac = [r for r in oks if r["family"] in ("A", "B")]
        print("G_geom = W_cl (equality observed) in", sum(1 for r in lac if r["G_geom_equals_W_cl"]), "of", len(lac), "lacunary pencils")
        print("max MV checked:", max(r["MV"] for r in oks))
    return results


if __name__ == "__main__":
    budget = float(sys.argv[1]) if len(sys.argv) > 1 else None
    main(budget)